aliases:
  - &publish-command
    name: Publish
    command: |
      COMMIT_MESSAGE=`git log --format=%s -n 1 $CIRCLE_SHA1`
      ./node_modules/.bin/node-pre-gyp rebuild package testpackage $PRE_GYP_ARGS
      if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then
        ./node_modules/.bin/node-pre-gyp package testpackage $PRE_GYP_ARGS
        ./node_modules/.bin/node-pre-gyp publish $PRE_GYP_ARGS
      else
        echo "Not a tagged build - not publishing"
      fi

  - &common-build
    resource_class: large
    working_directory: ~/repo
    steps:
      - checkout
      # Install git-lfs (not part of the standard Docker images)- run: sudo apt-get update
      - run: curl -sSL https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - run: sudo apt-get update && sudo apt-get install -y git-lfs && git-lfs install --force && git-lfs pull
      - run: npm install --build-from-source

      - run: npm run test
      - run: *publish-command


  - &common-electron-linux
    resource_class: large
    docker:
      - image: circleci/node:10.16.0

    working_directory: ~/repo

    steps:
      - checkout
      # Install git-lfs (not part of the standard Docker images)
      - run: curl -sSL https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - run: sudo apt-get update && sudo apt-get install -y git-lfs && git-lfs install --force && git-lfs pull
      # These are required for electron(-mocha)
      - run: sudo apt-get install -y libgtk2.0-0 libgtk-3-dev libxtst6 libxss1 libgconf2-4 libnss3 libasound2
      - run: npm install --build-from-source
      - run: ./node_modules/.bin/electron-rebuild
      - run: npm run pretest
      - run: xvfb-run ./node_modules/.bin/electron-mocha --timeout 480000
      - run: *publish-command

  - &common-macos
    resource_class: large
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew install git-lfs openssl@1.1 || true
      - run: git lfs install
      - run: git lfs pull
      - run:
          name: Install Node
          command: |
            source ~/.bash_profile

            # Install the correct Node version
            curl --silent -o node.tar.xz https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-darwin-x64.tar.xz
            tar xf node.tar.xz
            echo 'export NODE_PATH=$HOME/node' >> $BASH_ENV
            echo 'export PATH=$NODE_PATH/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            mv node-v$NODE_VERSION-darwin-x64 $NODE_PATH
            node -v

      - run:
          name: Install & Build
          command: |
            node -v
            npm install --build-from-source

      - run: npm run test
      - run: ./node_modules/.bin/electron-rebuild
      - run: ./node_modules/.bin/electron-mocha --timeout 480000
      - run:
          <<: *publish-command

version: 2
jobs:
  build-12.6.0:
    <<: *common-build
    docker:
      - image: circleci/node:12.6.0

  build-10.16.0:
    <<: *common-build
    docker:
      - image: circleci/node:10.16.0

  build-8.16.0:
    <<: *common-build
    docker:
      - image: circleci/node:8.16.0

  build-electron-8.1.1:
    <<: *common-electron-linux
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=8.1.1 --disturl=https://atom.io/download/electron

  build-electron-7.1.14:
    <<: *common-electron-linux
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=7.1.14 --disturl=https://atom.io/download/electron

  build-electron-6.1.9:
    <<: *common-electron-linux
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=6.1.9 --disturl=https://atom.io/download/electron


  build-electron-5.0.6:
    <<: *common-electron-linux
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=5.0.6 --disturl=https://atom.io/download/electron

  build-electron-4.2.6:
    <<: *common-electron-linux
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=4.2.6 --disturl=https://atom.io/download/electron

  build-electron-3.1.11:
    <<: *common-electron-linux
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=3.1.11 --disturl=https://atom.io/download/electron

  build-electron-2.0.18:
    <<: *common-electron-linux
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=2.0.18 --disturl=https://atom.io/download/electron

  build-macos-12.6.0:
    <<: *common-macos
    environment:
      NODE_VERSION: "12.6.0"

  build-macos-10.16.0:
    <<: *common-macos
    environment:
      NODE_VERSION: "10.16.0"

  build-macos-electron-8.1.1:
    <<: *common-macos
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=8.1.1 --disturl=https://atom.io/download/electron
      NODE_VERSION: "10.16.0"

  build-macos-electron-7.1.14:
    <<: *common-macos
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=7.1.14 --disturl=https://atom.io/download/electron
      NODE_VERSION: "10.16.0"

  build-macos-electron-6.1.9:
    <<: *common-macos
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=6.1.9 --disturl=https://atom.io/download/electron
      NODE_VERSION: "10.16.0"

  build-macos-electron-5.0.6:
    <<: *common-macos
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=5.0.6 --disturl=https://atom.io/download/electron
      NODE_VERSION: "10.16.0"

  build-macos-electron-4.2.6:
    <<: *common-macos
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=4.2.6 --disturl=https://atom.io/download/electron
      NODE_VERSION: "10.16.0"

  build-macos-electron-3.1.11:
    <<: *common-macos
    environment:
      PRE_GYP_ARGS: --runtime=electron --target=3.1.11 --disturl=https://atom.io/download/electron
      NODE_VERSION: "10.16.0"

workflows:
  version: 2
  build_all:
    jobs:
      - build-12.6.0
      - build-10.16.0
      - build-8.16.0
      - build-electron-8.1.1
      - build-electron-7.1.14
      - build-electron-6.1.9
      - build-electron-5.0.6
      - build-electron-4.2.6
      - build-electron-3.1.11
      - build-electron-2.0.18
      - build-electron-5.0.6
      - build-macos-12.6.0
      - build-macos-10.16.0
      - build-macos-electron-8.1.1
      - build-macos-electron-7.1.14
      - build-macos-electron-6.1.9
      - build-macos-electron-5.0.6
      - build-macos-electron-4.2.6
      - build-macos-electron-3.1.11
